# -*- coding: utf-8 -*-
"""NYdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXCMviVSjN-FTiRng3fkMtcIw1K7L6pA

## Análise de Dados do Airbnb em Nova York: Tendências, Preços e Disponibilidade
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('AB_NYC_2019.csv')
data.head(3) # comando para reconhecer os dados

"""### **Dados de preço por região**"""

#aplicando método "agg()" para realizar mais de uma operação
estatisticas_por_regiao = data.groupby('neighbourhood_group').agg(
    max_preco=('price', 'max'),
    media_preco=('price', 'mean'),
    min_preco=('price', 'min'),
    total_listagens=('calculated_host_listings_count', 'sum'),
    avaliacao_media=('reviews_per_month', 'mean')
).reset_index()

# Exibindo a tabela resultante
display(estatisticas_por_regiao)

"""Nesta tabela podemos analisar os dados por região pelo preço máximo, minímo, médio e total.

### Análise de Tipos de Acomodação
"""

acomodacao = data['room_type']
regiao = data['neighbourhood_group']

# VISUALIZAÇÃO DE DADOS

plt.figure(figsize=(10, 6))
sns.countplot(x=acomodacao, hue=regiao)
plt.title('Distribuição de Tipos de Acomodação por Região')
plt.xlabel('Tipos de Acomodação por região')
plt.ylabel('Quantidade')
plt.xticks(rotation=45)
plt.legend(title='Região')
plt.show()

# Iterar sobre cada região e criar gráficos de pizza
regioes = data['neighbourhood_group'].unique()

for regiao in regioes:
    # Filtrar os dados por região
    dados_regiao = data[data['neighbourhood_group'] == regiao]

    # Contar os tipos de acomodação
    tipos_acomodacao = dados_regiao['room_type'].value_counts()

    # Plotar o gráfico de pizza
    plt.figure(figsize=(6, 6))
    plt.pie(
        tipos_acomodacao,
        labels=tipos_acomodacao.index,
        autopct='%1.1f%%',
        startangle=90,
        colors=sns.color_palette('Set2', n_colors=len(tipos_acomodacao))
    )
    plt.title(f'Distribuição de Tipos de Acomodação - {regiao}', fontsize=14)
    plt.axis('equal')  # Assegura que o gráfico seja um círculo
    plt.tight_layout()
    plt.show()

"""Neste gráfico podemos ver a frequência de cada categoria e sua estatística.

# Distribuição de preços

# Pergunta: Qual a faixa de preço predominante por tipo de acomodação?
"""

tipo_de_acomodacao = data['room_type']
preco = data['price']

# Configurando a figura
plt.figure(figsize=(12, 8))

# Criando o boxplot
sns.boxplot(
    x='room_type',
    y='price',
    data=data,
    palette='Set1',
    hue='neighbourhood_group',
    showfliers=False  # Oculta outliers para uma visualização mais limpa
)

# Ajustando o gráfico
plt.title('Distribuição de Preços por Tipo de Acomodação', fontsize=16)
plt.xlabel('Tipo de Acomodação', fontsize=12)
plt.ylabel('Preço (USD)', fontsize=12)
plt.xticks(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='Região', fontsize=10)
plt.tight_layout()
plt.show()

"""📌 Principais Observações
"Entire home/apt" tem a maior variação de preços

Os preços são significativamente mais altos e variáveis para esse tipo de acomodação, especialmente em Manhattan e Brooklyn.
Há outliers indicando algumas listagens com preços extremamente elevados.
"Private room" tem uma faixa de preços mais estável

A maioria dos valores está entre 50 e 150 USD, dependendo da região.
Manhattan apresenta preços um pouco mais altos e dispersos.
"Shared room" tem os preços mais baixos

Os preços são mais uniformes e bem abaixo das outras categorias.
As medianas das regiões são próximas entre si, indicando uma menor variação de preços entre os bairros para este tipo de acomodação.
Diferentes regiões apresentam variações distintas

Manhattan tende a ter preços mais elevados e dispersos, principalmente para apartamentos inteiros.
Brooklyn também apresenta alta variação de preços, mas com valores um pouco mais baixos do que Manhattan.
Queens, Bronx e Staten Island possuem preços mais acessíveis e menos dispersos.
📊 O que esse boxplot pode indicar?
Viajantes com orçamento menor podem preferir Private rooms ou Shared rooms em regiões como Queens ou Bronx.
Proprietários podem ajustar os preços com base na região e no tipo de acomodação para competir no mercado.
Análises futuras podem verificar se a demanda e as avaliações justificam essas diferenças de preços.
Se precisar de mais detalhes ou quiser ajustes no gráfico, me avise! 🚀

### Popularidade por Região
"""

# Calculando a média de avaliações por bairro
media_avaliacoes = data.groupby('neighbourhood')['number_of_reviews'].mean().reset_index()

# Renomeando as colunas para legibilidade
media_avaliacoes.columns = ['Bairro', 'Média de Avaliações']

# Ordenando os bairros pela média de avaliações em ordem decrescente
media_avaliacoes = media_avaliacoes.sort_values(by='Média de Avaliações', ascending=False)

# Exibindo os 10 bairros com maior média de avaliações
display(media_avaliacoes.head(10))

"""### Visualização"""

# Configurando o gráfico de barras
plt.figure(figsize=(12, 8))
sns.barplot(
    data=media_avaliacoes.head(10),  # Os 10 bairros mais populares
    x='Média de Avaliações',
    y='Bairro',
    palette='coolwarm'
)

# Ajustando o gráfico
plt.title('Top 10 Bairros com Maior Média de Avaliações', fontsize=16)
plt.xlabel('Média de Avaliações', fontsize=12)
plt.ylabel('Bairro', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()